services:
  - type: web
    name: mistress-wishlist
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.webapp:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: BOT_TOKEN
        sync: false
      - key: MOD_CHAT_IDS
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
